name: Build SKIA
on: workflow_dispatch
jobs:
  build:
    runs-on: macos-latest-xlarge
    strategy:
      matrix:
        include:
          # Apple individual targets
          - target: "apple-arm64-iphoneos"
            artifact_name: "skia-apple-arm64-iphoneos"
            artifact_path: "./externals/skia/out/apple/arm64-iphoneos/*.a"
          - target: "apple-arm64-iphonesimulator"
            artifact_name: "skia-apple-arm64-iphonesimulator"
            artifact_path: "./externals/skia/out/apple/arm64-iphonesimulator/*.a"
          - target: "apple-x64-iphonesimulator"
            artifact_name: "skia-apple-x64-iphonesimulator"
            artifact_path: "./externals/skia/out/apple/x64-iphonesimulator/*.a"
          - target: "apple-arm64-macosx"
            artifact_name: "skia-apple-arm64-macosx"
            artifact_path: "./externals/skia/out/apple/arm64-macosx/*.a"
          - target: "apple-x64-macosx"
            artifact_name: "skia-apple-x64-macosx"
            artifact_path: "./externals/skia/out/apple/x64-macosx/*.a"
          - target: "apple-arm64-tvos"
            artifact_name: "skia-apple-arm64-tvos"
            artifact_path: "./externals/skia/out/apple/arm64-tvos/*.a"
          - target: "apple-arm64-tvsimulator"
            artifact_name: "skia-apple-arm64-tvsimulator"
            artifact_path: "./externals/skia/out/apple/arm64-tvsimulator/*.a"
          - target: "apple-x64-tvsimulator"
            artifact_name: "skia-apple-x64-tvsimulator"
            artifact_path: "./externals/skia/out/apple/x64-tvsimulator/*.a"
          # Android targets
          - target: "android-arm"
            artifact_name: "skia-android-arm"
            artifact_path: |
              ./externals/skia/out/android/arm/libskia.a
              ./externals/skia/out/android/arm/libskshaper.a
              ./externals/skia/out/android/arm/libsvg.a
              ./externals/skia/out/android/arm/libskottie.a
              ./externals/skia/out/android/arm/libsksg.a
              ./externals/skia/out/android/arm/libskparagraph.a
              ./externals/skia/out/android/arm/libskunicode_core.a
              ./externals/skia/out/android/arm/libskunicode_icu.a
              ./externals/skia/out/android/arm/libpathops.a
              ./externals/skia/out/android/arm/libjsonreader.a
          - target: "android-arm64"
            artifact_name: "skia-android-arm-64"
            artifact_path: |
              ./externals/skia/out/android/arm64/libskia.a
              ./externals/skia/out/android/arm64/libskshaper.a
              ./externals/skia/out/android/arm64/libsvg.a
              ./externals/skia/out/android/arm64/libskottie.a
              ./externals/skia/out/android/arm64/libsksg.a
              ./externals/skia/out/android/arm64/libskparagraph.a
              ./externals/skia/out/android/arm64/libskunicode_core.a
              ./externals/skia/out/android/arm64/libskunicode_icu.a
              ./externals/skia/out/android/arm64/libpathops.a
              ./externals/skia/out/android/arm64/libjsonreader.a
          - target: "android-x86"
            artifact_name: "skia-android-arm-x86"
            artifact_path: |
              ./externals/skia/out/android/x86/libskia.a
              ./externals/skia/out/android/x86/libskshaper.a
              ./externals/skia/out/android/x86/libsvg.a
              ./externals/skia/out/android/x86/libskottie.a
              ./externals/skia/out/android/x86/libsksg.a
              ./externals/skia/out/android/x86/libskparagraph.a
              ./externals/skia/out/android/x86/libskunicode_core.a
              ./externals/skia/out/android/x86/libskunicode_icu.a
              ./externals/skia/out/android/x86/libpathops.a
              ./externals/skia/out/android/x86/libjsonreader.a
          - target: "android-x64"
            artifact_name: "skia-android-arm-x64"
            artifact_path: |
              ./externals/skia/out/android/x64/libskia.a
              ./externals/skia/out/android/x64/libskshaper.a
              ./externals/skia/out/android/x64/libsvg.a
              ./externals/skia/out/android/x64/libskottie.a
              ./externals/skia/out/android/x64/libsksg.a
              ./externals/skia/out/android/x64/libskparagraph.a
              ./externals/skia/out/android/x64/libskunicode_core.a
              ./externals/skia/out/android/x64/libskunicode_icu.a
              ./externals/skia/out/android/x64/libpathops.a
              ./externals/skia/out/android/x64/libjsonreader.a
      fail-fast: false
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: recursive

      - name: Setup Android NDK
        id: setup-ndk
        if: startsWith(matrix.target, 'android')
        uses: nttld/setup-ndk@afb4c9964b521afb97c864b7d40b11e6911bd410 # v1.5.0
        with:
          ndk-version: r22b

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Setup
        uses: ./.github/actions/setup
        with:
          download_skia: 'false'
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update depot_tools
        working-directory: ./externals/depot_tools
        run: ./update_depot_tools

      - name: Build Skia - ${{ matrix.target }}
        working-directory: ./packages/skia
        env:
          ANDROID_NDK: ${{ steps.setup-ndk.outputs.ndk-path }}
          GIT_SYNC_DEPS_SKIP_EMSDK: 'true'
          ZERO_AR_DATE: 1
        run: yarn build-skia ${{ matrix.target }}

      - name: Upload artifacts - ${{ matrix.artifact_name }}
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_path }}

  package-apple:
    name: Package Apple XCFrameworks
    runs-on: macos-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    env:
      GRAPHITE: ${{ contains(github.workflow, 'Graphite') }}
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: recursive

      - name: Download all Apple build artifacts
        uses: actions/download-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          pattern: skia-apple-*
          path: artifacts

      - name: Setup
        uses: ./.github/actions/setup
        with:
          download_skia: 'false'
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy artifacts to expected locations
        working-directory: ./externals/skia
        run: |
          # Copy individual architecture files to expected locations
          mkdir -p out/apple/arm64-iphoneos out/apple/arm64-iphonesimulator out/apple/x64-iphonesimulator 
          mkdir -p out/apple/arm64-macosx out/apple/x64-macosx
          mkdir -p out/apple/arm64-tvos out/apple/arm64-tvsimulator out/apple/x64-tvsimulator
          
          cp artifacts/skia-apple-arm64-iphoneos/*.a out/apple/arm64-iphoneos/
          cp artifacts/skia-apple-arm64-iphonesimulator/*.a out/apple/arm64-iphonesimulator/
          cp artifacts/skia-apple-x64-iphonesimulator/*.a out/apple/x64-iphonesimulator/
          cp artifacts/skia-apple-arm64-macosx/*.a out/apple/arm64-macosx/
          cp artifacts/skia-apple-x64-macosx/*.a out/apple/x64-macosx/
          
          # Copy tvOS artifacts if they exist (not present in Graphite builds)
          if [ -d "artifacts/skia-apple-arm64-tvos" ]; then
            cp artifacts/skia-apple-arm64-tvos/*.a out/apple/arm64-tvos/
            cp artifacts/skia-apple-arm64-tvsimulator/*.a out/apple/arm64-tvsimulator/
            cp artifacts/skia-apple-x64-tvsimulator/*.a out/apple/x64-tvsimulator/
          fi

      - name: Build XCFrameworks
        working-directory: ./packages/skia
        env:
          SK_GRAPHITE: ${{ contains(github.workflow, 'Graphite') && '1' || '' }}
        run: yarn build-xcframeworks

      - name: Copy headers
        working-directory: ./packages/skia
        run: yarn copy-skia-headers

      - name: Upload Apple XCFrameworks
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: skia-apple-xcframeworks
          path: ./packages/skia/libs/apple/*.xcframework